
DROP TABLE IF EXISTS WATER_READING_DETAILS;
DROP TABLE IF EXISTS USER_INFO;

CREATE TABLE USER_INFO (
                           USERID INT AUTO_INCREMENT  PRIMARY KEY,
                             RRNO INT UNIQUE KEY,
                                       FIRSTNAME VARCHAR(250) NOT NULL,
                                       LASTNAME VARCHAR(250) NOT NULL,
                                       ADDRESS VARCHAR(250) NOT NULL,
                                       USERTYPE VARCHAR(250) NOT NULL,
                                       CREATED_TME timestamp DEFAULT CURRENT_TIMESTAMP,
                                       MODIFIED_TIME timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE WATER_READING_DETAILS (
  RRNO INT PRIMARY KEY,
  CURRENT_METER_READING INT(100) NOT NULL,
  PREVIOUS_METER_READING INT(100) NOT NULL,
  WATER_CONSUMPTION_LITRE INT(100) NOT NULL,
  AMOUNT DECFLOAT(20)  NOT NULL,
  BILLEDMONTH DATE NOT NULL,
  CREATED_TME timestamp DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_TIME timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

--INSERT INTO WATER_READING_DETAILS (WATERCONSUMPTIONLITRE,AMOUNT,BILLEDMONTH) VALUES ("250","2100.44","MAR2002");
--INSERT INTO WATER_READING_DETAILS (WATERCONSUMPTIONLITRE,AMOUNT,BILLEDMONTH) VALUES ("20","400.44","MAR2002");