
DROP TABLE IF EXISTS WATER_METER_READING 
DROP TABLE IF EXISTS USER_INFO

CREATE TABLE WATER_METER_READING (
  USERID INT AUTO_INCREMENT  PRIMARY KEY,
  WATERCONSUMPTIONLITRE VARCHAR(250) NOT NULL,
  AMOUNT VARCHAR(250) NOT NULL,
  MONYYYY VARCHAR(250) NOT NULL,
  CREATED_TME timestamp,
  MODIFIED_TIME timestamp
);

CREATE TABLE USER_INFO (
  USERID INT AUTO_INCREMENT  PRIMARY KEY,
  WATERCONSUMPTIONLITRE VARCHAR(250) NOT NULL,
  AMOUNT VARCHAR(250) NOT NULL,
  MONYYYY VARCHAR(250) NOT NULL
);