
DROP TABLE IF EXISTS WATER_READING_DETAILS

CREATE TABLE WATER_READING_DETAILS (
  USERID INT AUTO_INCREMENT  PRIMARY KEY,
  WATERCONSUMPTIONLITRE VARCHAR(250) NOT NULL,
  AMOUNT VARCHAR(250) NOT NULL,
  BILLEDMONTH VARCHAR(250) NOT NULL,
  CREATED_TME timestamp,
  MODIFIED_TIME timestamp
);

INSERT INTO WATER_READING_DETAILS (WATERCONSUMPTIONLITRE,AMOUNT,BILLEDMONTH) VALUES ("250","2100.44","MAR2002");
INSERT INTO WATER_READING_DETAILS (WATERCONSUMPTIONLITRE,AMOUNT,BILLEDMONTH) VALUES ("20","400.44","MAR2002");